name="Level 6"
follow_distance = 4

[[doors]]
id = 133
x = 6
y = 0
[doors.type]
type = "NorthSouth"
[doors.state]
state = "Closed"

[[doors]]
id = 134
x = 5
y = 1
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 135
x = 0
y = 5
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 136
x = 10
y = 7
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 137
x = 12
y = 7
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 138
x = 14
y = 7
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 139
x = 16
y = 7
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 140
x = 18
y = 7
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 141
x = 7
y = 13
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 142
x = 10
y = 13
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 143
x = 12
y = 13
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 144
x = 14
y = 13
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 145
x = 16
y = 13
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 146
x = 18
y = 13
[doors.type]
type = "EastWest"
[doors.state]
state = "Closed"

[[doors]]
id = 147
x = 3
y = 12
[doors.type]
type = "NorthSouth"
[doors.state]
state = "Closed"

[finish]
id = 166
x = 7
y = 12

[[spikeballs]]
id = 110
x = 9
y = 0
[spikeballs.dir]
dir = "South"
[spikeballs.clip]
clip = "Clip"

[[spikeballs]]
id = 111
x = 12
y = 1
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 112
x = 5
y = 2
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 113
x = 10
y = 2
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 114
x = 15
y = 2
[spikeballs.dir]
dir = "South"
[spikeballs.clip]
clip = "Clip"

[[spikeballs]]
id = 115
x = 17
y = 2
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 116
x = 14
y = 3
[spikeballs.dir]
dir = "South"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 117
x = 2
y = 4
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Clip"

[[spikeballs]]
id = 118
x = 18
y = 4
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Clip"

[[spikeballs]]
id = 119
x = 3
y = 6
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 120
x = 4
y = 8
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Clip"

[[spikeballs]]
id = 121
x = 3
y = 11
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Clip"

[[spikeballs]]
id = 122
x = 10
y = 14
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 123
x = 12
y = 14
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 124
x = 14
y = 14
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 125
x = 16
y = 14
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[[spikeballs]]
id = 126
x = 18
y = 14
[spikeballs.dir]
dir = "North"
[spikeballs.clip]
clip = "Block"

[start]
id = 165
x = 19
y = 12

[[switches]]
id = 148
x = 5
y = 0
toggles = [ 141 ]

[[switches]]
id = 149
x = 1
y = 1
toggles = [ 135 ]

[[switches]]
id = 150
x = 3
y = 1

toggles = [ 134, 133 ]

[[switches]]
id = 151
x = 7
y = 1

toggles = [ 134, 133 ]

[[switches]]
id = 152
x = 1
y = 8
toggles = [ 135 ]

[[switches]]
id = 153
x = 9
y = 12
toggles = [ 136 ]

[[switches]]
id = 154
x = 10
y = 12
toggles = [ 142 ]

[[switches]]
id = 155
x = 11
y = 12
toggles = [ 137 ]

[[switches]]
id = 156
x = 12
y = 12
toggles = [ 143 ]

[[switches]]
id = 157
x = 13
y = 12
toggles = [ 138 ]

[[switches]]
id = 158
x = 14
y = 12
toggles = [ 144 ]

[[switches]]
id = 159
x = 15
y = 12
toggles = [ 139 ]

[[switches]]
id = 160
x = 16
y = 12
toggles = [ 145 ]

[[switches]]
id = 161
x = 17
y = 12
toggles = [ 140 ]

[[switches]]
id = 162
x = 18
y = 12
toggles = [ 146 ]

[[switches]]
id = 163
x = 2
y = 14
toggles = [ 147 ]

[[switches]]
id = 164
x = 4
y = 14
toggles = [ 147 ]

[[teleports]]
id = 127
tx = 0
ty = 2
x = 0
y = 1

[[teleports]]
id = 128
tx = 2
ty = 8
x = 2
y = 3

[[teleports]]
id = 129
tx = 3
ty = 8
x = 3
y = 3

[[teleports]]
id = 130
tx = 4
ty = 8
x = 4
y = 3

[[teleports]]
id = 131
tx = 8
ty = 8
x = 6
y = 3

[[teleports]]
id = 132
tx = 19
ty = 6
x = 8
y = 12

[[walls]]
id = 0
x = 0
y = 0

[[walls]]
id = 1
x = 2
y = 1

[[walls]]
id = 2
x = 4
y = 1

[[walls]]
id = 3
x = 6
y = 1

[[walls]]
id = 4
x = 8
y = 1

[[walls]]
id = 5
x = 11
y = 1

[[walls]]
id = 6
x = 13
y = 1

[[walls]]
id = 7
x = 16
y = 1

[[walls]]
id = 8
x = 1
y = 2

[[walls]]
id = 9
x = 2
y = 2

[[walls]]
id = 10
x = 3
y = 2

[[walls]]
id = 11
x = 4
y = 2

[[walls]]
id = 12
x = 6
y = 2

[[walls]]
id = 13
x = 7
y = 2

[[walls]]
id = 14
x = 8
y = 2

[[walls]]
id = 15
x = 1
y = 3

[[walls]]
id = 16
x = 5
y = 3

[[walls]]
id = 17
x = 7
y = 3

[[walls]]
id = 18
x = 8
y = 3

[[walls]]
id = 19
x = 11
y = 3

[[walls]]
id = 20
x = 13
y = 3

[[walls]]
id = 21
x = 16
y = 3

[[walls]]
id = 22
x = 1
y = 4

[[walls]]
id = 23
x = 7
y = 4

[[walls]]
id = 24
x = 1
y = 5

[[walls]]
id = 25
x = 7
y = 5

[[walls]]
id = 26
x = 9
y = 5

[[walls]]
id = 27
x = 10
y = 5

[[walls]]
id = 28
x = 11
y = 5

[[walls]]
id = 29
x = 12
y = 5

[[walls]]
id = 30
x = 13
y = 5

[[walls]]
id = 31
x = 14
y = 5

[[walls]]
id = 32
x = 15
y = 5

[[walls]]
id = 33
x = 16
y = 5

[[walls]]
id = 34
x = 17
y = 5

[[walls]]
id = 35
x = 18
y = 5

[[walls]]
id = 36
x = 19
y = 5

[[walls]]
id = 37
x = 1
y = 6

[[walls]]
id = 38
x = 7
y = 6

[[walls]]
id = 39
x = 1
y = 7

[[walls]]
id = 40
x = 7
y = 7

[[walls]]
id = 41
x = 8
y = 7

[[walls]]
id = 42
x = 9
y = 7

[[walls]]
id = 43
x = 11
y = 7

[[walls]]
id = 44
x = 13
y = 7

[[walls]]
id = 45
x = 15
y = 7

[[walls]]
id = 46
x = 17
y = 7

[[walls]]
id = 47
x = 19
y = 7

[[walls]]
id = 48
x = 7
y = 8

[[walls]]
id = 49
x = 9
y = 8

[[walls]]
id = 50
x = 11
y = 8

[[walls]]
id = 51
x = 13
y = 8

[[walls]]
id = 52
x = 15
y = 8

[[walls]]
id = 53
x = 17
y = 8

[[walls]]
id = 54
x = 19
y = 8

[[walls]]
id = 55
x = 0
y = 9

[[walls]]
id = 56
x = 1
y = 9

[[walls]]
id = 57
x = 2
y = 9

[[walls]]
id = 58
x = 3
y = 9

[[walls]]
id = 59
x = 4
y = 9

[[walls]]
id = 60
x = 5
y = 9

[[walls]]
id = 61
x = 6
y = 9

[[walls]]
id = 62
x = 7
y = 9

[[walls]]
id = 63
x = 9
y = 9

[[walls]]
id = 64
x = 11
y = 9

[[walls]]
id = 65
x = 13
y = 9

[[walls]]
id = 66
x = 15
y = 9

[[walls]]
id = 67
x = 17
y = 9

[[walls]]
id = 68
x = 19
y = 9

[[walls]]
id = 69
x = 9
y = 10

[[walls]]
id = 70
x = 11
y = 10

[[walls]]
id = 71
x = 13
y = 10

[[walls]]
id = 72
x = 15
y = 10

[[walls]]
id = 73
x = 17
y = 10

[[walls]]
id = 74
x = 19
y = 10

[[walls]]
id = 75
x = 1
y = 11

[[walls]]
id = 76
x = 2
y = 11

[[walls]]
id = 77
x = 4
y = 11

[[walls]]
id = 78
x = 5
y = 11

[[walls]]
id = 79
x = 6
y = 11

[[walls]]
id = 80
x = 7
y = 11

[[walls]]
id = 81
x = 8
y = 11

[[walls]]
id = 82
x = 9
y = 11

[[walls]]
id = 83
x = 11
y = 11

[[walls]]
id = 84
x = 13
y = 11

[[walls]]
id = 85
x = 15
y = 11

[[walls]]
id = 86
x = 17
y = 11

[[walls]]
id = 87
x = 19
y = 11

[[walls]]
id = 88
x = 1
y = 12

[[walls]]
id = 89
x = 5
y = 12

[[walls]]
id = 90
x = 6
y = 12

[[walls]]
id = 91
x = 1
y = 13

[[walls]]
id = 92
x = 3
y = 13

[[walls]]
id = 93
x = 5
y = 13

[[walls]]
id = 94
x = 6
y = 13

[[walls]]
id = 95
x = 8
y = 13

[[walls]]
id = 96
x = 9
y = 13

[[walls]]
id = 97
x = 11
y = 13

[[walls]]
id = 98
x = 13
y = 13

[[walls]]
id = 99
x = 15
y = 13

[[walls]]
id = 100
x = 17
y = 13

[[walls]]
id = 101
x = 19
y = 13

[[walls]]
id = 102
x = 3
y = 14

[[walls]]
id = 103
x = 8
y = 14

[[walls]]
id = 104
x = 9
y = 14

[[walls]]
id = 105
x = 11
y = 14

[[walls]]
id = 106
x = 13
y = 14

[[walls]]
id = 107
x = 15
y = 14

[[walls]]
id = 108
x = 17
y = 14

[[walls]]
id = 109
x = 19
y = 14
